# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: GlaciusLabs.Markitect
PackageVersion: 0.5.0
InstallerType: portable
Commands:
- markitect
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Glacius-Labs/Markitect/releases/download/v0.5.0/markitect-v0.5.0-windows-amd64.exe
  InstallerSha256: 6F5B98DAD2EA6003BC0368800691AF70084A44D2C225C26FE12D120BCDA27178
ManifestType: installer
ManifestVersion: 1.12.0

